# Meadow.Core pipeline
# Reference: https://aka.ms/yaml

resources:
  repositories:
    - repository: MeadowCore
      type: github
      endpoint: WildernessLabs
      name: WildernessLabs/Meadow.Core
    - repository: MeadowContracts
      type: github
      endpoint: WildernessLabs
      name: WildernessLabs/Meadow.Contracts
    - repository: MeadowUnits
      type: github
      endpoint: WildernessLabs
      name: WildernessLabs/Meadow.Units
    - repository: MeadowLogging
      type: github
      endpoint: WildernessLabs
      name: WildernessLabs/Meadow.Logging

trigger:
  - main
  - develop
  - staging
  - release

variables:
  solution: "**/Meadow.Core.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  internalFeedName: "Meadow.Staging"

pool:
  vmImage: windows-2019

stages:
  - stage: Build
    jobs:
      - job: Build_Solution
        steps:
          - checkout: self
          - checkout: MeadowContracts
          - checkout: MeadowUnits
          - checkout: MeadowLogging
          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            displayName: Use_Nugets
            inputs:
              feedsToUse: "select"
              vstsFeed: $(internalFeedName) #use internal feed
              restoreSolution: "$(solution)"
          - task: VSBuild@1
            inputs:
              solution: "$(solution)"
              platform: "$(buildPlatform)"
              configuration: "$(buildConfiguration)"
              msbuildArgs: /property:langversion=latest
          - task: CopyFiles@2
            inputs:
              Contents: '**\*.nupkg'
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
              flattenFolders: true
              cleanTargetFolder: true
              overWrite: true
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: packages
